development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: kvb_tracker_development

staging:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: kvb_tracker_staging

test: &test
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: kvb_tracker_test

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  database: kvb_tracker_production
